channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - dill==0.3.7
  - fsspec==2023.6.0
  - numpy==1.26.0
  - packaging==23.2
  - pandas==2.1.1
  - protobuf==4.24.4
  - pydot==1.4.2
  - requests==2.31.0
  - scipy==1.11.3
  - tensorflow==2.14.0
name: mlflow-env
